### ISSUE TITLE
[Tracking] Expand boilerplate to include more feature examples

### ISSUE THREAD

**Issue by sandreae** [p2panda/tauri-example#1]
* [x] embeded aquadoggo in a tauri app
* tauri config example
    * [x] basic
    * [x] persistence storage for config, blobs and private key #5 
    * [x] networking permissions
    * [x] fs permissions
* [x] w/ multi-platform compile CI https://github.com/p2panda/tauri-example/pull/3
* [x] example aquadoggo configuration flow (importing config, persistence locations)
* [x] use of `shirokuma` in the front-end
    * [x] key pair generation
    * [x] publish data
* [x] simple GraphQL query
* [x] create schema on startup
* [x] multiple peers each with own tmp storage

All remaining tasks closed by #7
